export const Constants = {
  ENV: {
    APP_NAME: 'APP_NAME',
    APP_DESCRIPTION: 'APP_DESCRIPTION',
    APP_VERSION: 'APP_VERSION',
    APP_PORT: 'APP_PORT',
    DEV: 'development',
    AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID',
    AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY',
    AWS_REGION: 'AWS_REGION',
  },
};
